/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/platform-raised.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[0, -1.3, 0]}
        scale={[18.68 / 4.7, 4.12 / 4.7, 34.62 / 4.7]}
        rotation={[0, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/platform-raised.gltf");
